/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import cn.com.crowdsourcedtesting.struts.form.BugReportManagementForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/bugReportManagement" name="bugReportManagementForm" parameter="method" scope="request" validate="true"
 */
public class BugReportManagementAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward bugReportList(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BugReportManagementForm bugReportManagementForm = (BugReportManagementForm) form;
		System.out.println(bugReportManagementForm.getBugReportId());
		System.out.println(bugReportManagementForm.getTaskId());
		
		
		
		return mapping.findForward("bugReportDetail");
	}
}