/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;
import org.apache.struts.actions.DispatchAction;

import cn.com.crowdsourcedtesting.bean.Publisher;
import cn.com.crowdsourcedtesting.struts.form.EditTaskForm;

/**
 * MyEclipse Struts Creation date: 05-26-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/editTask" name="editTaskForm"
 *                input="/form/editTask.jsp" scope="request" validate="true"
 */
public class EditTaskAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward submitCloseForm(ActionMapping mapping,
			ActionForm form, HttpServletRequest request,
			HttpServletResponse response) {
		EditTaskForm editTaskForm = (EditTaskForm) form;// TODO Auto-generated
														// method stub
		Publisher publisher = (Publisher) request.getSession().getAttribute(
				"Publisher");
		if (publisher == null) {
			return new ActionRedirect(
					mapping.findForwardConfig("publisherLogin"));
		}
		if (editTaskForm.getTaskID() == null) {
			return new ActionRedirect(mapping.findForwardConfig("checkList"));
		}
		return mapping.findForward("taskCloseForm");
	}

	public ActionForward closeMessage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return new ActionRedirect(mapping.findForwardConfig("checkList"));
	}
}