/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import cn.com.crowdsourcedtesting.DAO.GiftDAO;
import cn.com.crowdsourcedtesting.bean.Gift;
import cn.com.crowdsourcedtesting.model.GiftHandler;
import cn.com.crowdsourcedtesting.model.RecruitmentHandler;
import cn.com.crowdsourcedtesting.struts.form.GiftForm;
import cn.com.other.page.Page;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/gift" name="giftForm" input="/gifts.jsp" scope="request" validate="true"
 */
public class GiftAction extends DispatchAction {
	
	private String gifttype = "all";
	private String searchvalue = "";
	
	private Page page = new Page();
	
	private GiftHandler handler = new GiftHandler();
	
	/*
	 * Generated Methods
	 */

	/** 
	 * Method selectGift
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward selectGift(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		int id = giftForm.getGiftId();

		handler.selectGift(request, id);
		
		return mapping.findForward("giftitem");
	}
	
	/** 
	 * Method selectPage
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward selectPage(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		int pagenow = giftForm.getPagenow();

		handler.selectPage(gifttype, this.searchvalue, request, pagenow);
		
		return mapping.findForward("allgifts");
	}
	
	/** 
	 * Method selectAllGifts
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward selectAllGifts(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		this.gifttype = "all";

		handler.selectAllGifts(request);
		
		return mapping.findForward("allgifts");
	}
	
	/** 
	 * Method selectAvailableGifts
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward selectAvailableGifts(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		this.gifttype = "available";
		
		handler.selectAvailableGifts(request);
		
		return mapping.findForward("allgifts");
	}
	
	/** 
	 * Method selectSimilarGifts
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward selectSimilarGifts(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		String value = giftForm.getSearchinput();
		this.gifttype = "similar";
		this.searchvalue = value;
		
		handler.selectSimilarGifts(value, request);
		
		return mapping.findForward("allgifts");
	}
	
	/** 
	 * Method getGift
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward getGift(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		//int id = giftForm.getGiftId();
		//System.out.println("now:"+id);
		
		if(handler.getGift(mapping, giftForm, request, response))
		{
			System.out.println("跳入adrress界面");
			return mapping.findForward("changegift");
		}
		else
		{
			return mapping.findForward("changegiftfailed");
		}
	}
	
	
	/** 
	 * Method changeGift
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward changeGift(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		GiftForm giftForm = (GiftForm) form;// TODO Auto-generated method stub
		
		if(handler.changeGift(mapping, giftForm, request, response))
			return mapping.findForward("changegiftsuccess");
		else
			return mapping.findForward("changegiftfailed");
		
	}
	
	
}