/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import cn.com.crowdsourcedtesting.struts.form.PublishTestingTaskForm;

/**
 * MyEclipse Struts Creation date: 05-24-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/publishTestingTask" name="publishTestingTaskForm"
 *                input="/form/publishTestingTask.jsp" parameter="method"
 *                scope="request" validate="true"
 */
public class PublishTestingTaskAction extends DispatchAction {
	public ActionForward goToPublish(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("pubTask");
	}

	public ActionForward taskManagement(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("taskManagement");
	}

	public ActionForward pubWeb(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("pubWeb");
	}

	public ActionForward pubAndroid(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("pubAndroid");
	}

	public ActionForward pubDesktop(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		return mapping.findForward("pubDesktop");
	}

	public ActionForward webSubmitForm(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PublishTestingTaskForm publishTestingForm = (PublishTestingTaskForm) form;
		System.out.println(publishTestingForm.getDescription());
		System.out.println(publishTestingForm.getWebName());
		System.out.println(publishTestingForm.getIcon().getFileName());
		System.out.println(publishTestingForm.getWebUrl());
		return mapping.findForward("productSuccess");
	}
	
	public ActionForward pubTask(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PublishTestingTaskForm publishTestingForm = (PublishTestingTaskForm) form;
		System.out.println(publishTestingForm.getDaterange());
		System.out.println(publishTestingForm.getPerReward());
		System.out.println(publishTestingForm.getWholeReward());
		return mapping.findForward("taskSuccess");
	}
}