/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import cn.com.crowdsourcedtesting.model.QuestionnaireHandler;
import cn.com.crowdsourcedtesting.struts.form.PublisherQuestionnaireForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-02-2014
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 */
public class QuestionnaireRouter extends DispatchAction {
	/*
	 * Generated Methods
	 */

	QuestionnaireHandler myHandler = new QuestionnaireHandler();
	
	/**
	 * 跳转到发布页面
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward goToPublish(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		   try {
				request.setCharacterEncoding("utf-8");
			} catch (UnsupportedEncodingException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
			   response.setContentType("text/html;charset=utf-8");
		return mapping.findForward("add");
	}
	/**
	 * 添加问卷
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward Publish(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub

		return mapping.findForward("add");
	}
	
	/**
	 * 创建问卷
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return
	 */
	public ActionForward createItem(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub


		PublisherQuestionnaireForm f =  (PublisherQuestionnaireForm)form;
		
		/*PrintWriter out;
		try {
			out = response.getWriter();
			out.print(f.getChoices());
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}*/
		
	 myHandler.createItem(f, request);
	  return mapping.findForward("add");
	}
}