/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import cn.com.crowdsourcedtesting.struts.form.LoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-29-2014
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="loginForm" input="/security/login.jsp" scope="request" validate="true"
 */
public class SecurityRouter extends DispatchAction {
	/*
	 * Generated Methods
	 */
	/** 
	 * 用户登录
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward login(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
//		LoginForm loginForm = (LoginForm) form;// TODO Auto-generated method stub
		
		LoginForm f= (LoginForm)form;
		
		System.out.println(f.getUsername());
		return null;
	}
}