/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;
import org.apache.struts.actions.DispatchAction;

import cn.com.crowdsourcedtesting.DAO.JoinTaskDAO;
import cn.com.crowdsourcedtesting.DAO.TestTaskDAO;
import cn.com.crowdsourcedtesting.bean.TestTask;
import cn.com.crowdsourcedtesting.bean.Tester;
import cn.com.crowdsourcedtesting.modelhelper.TaskType;
import cn.com.crowdsourcedtesting.struts.form.TestTaskDetailViewForm;

/**
 * MyEclipse Struts Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/testTaskDetailView" name="testTaskDetailViewForm"
 *                input="/form/testTaskDetailView.jsp" scope="request"
 *                validate="true"
 */
public class TestTaskDetailViewAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward detailView(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestTaskDetailViewForm testTaskDetailViewForm = (TestTaskDetailViewForm) form;
		Integer testTaskId = testTaskDetailViewForm.getTaskID();
		if (testTaskId == null) {
			return new ActionRedirect(mapping.findForwardConfig("dispPage"));
		}
		TestTaskDAO testTaskDAO = new TestTaskDAO();
		TestTask testTask = testTaskDAO.findById(testTaskId);
		if (testTask == null) {
			return new ActionRedirect(mapping.findForwardConfig("dispPage"));
		}
		request.getSession().setAttribute("TaskDetail", testTask);
		Tester tester = (Tester) request.getAttribute("Tester");
		if (tester != null) {
			JoinTaskDAO joinTaskDAO = new JoinTaskDAO();
			if (joinTaskDAO.isExist(tester, testTask)) {
				request.getSession().setAttribute("HasJoinedTask", "true");
			} else {
				request.getSession().setAttribute("HasJoinedTask", "false");
			}
		}
		return mapping.findForward("taskDetailPage");
	}
	
	public ActionForward joinTask(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestTaskDetailViewForm testTaskDetailViewForm = (TestTaskDetailViewForm) form;
		Integer testTaskId = testTaskDetailViewForm.getTaskID();
		if (testTaskId == null) {
			return new ActionRedirect(mapping.findForwardConfig("dispPage"));
		}
		Tester tester = (Tester) request.getSession().getAttribute("Tester");
		if (tester == null) {
			return new ActionRedirect(mapping.findForwardConfig("testerLogin"));
		}
		
		TestTaskDAO testTaskDAO = new TestTaskDAO();
		TestTask testTask = testTaskDAO.findById(testTaskId);
		JoinTaskDAO joinTaskDAO = new JoinTaskDAO();
		if (joinTaskDAO.isExist(tester, testTask)) {
			joinTaskDAO.addJoinTask(tester, testTask);
		}
		switch (testTask.getTaskType()) {
		case (TaskType.Web):
			return new ActionRedirect("http://www.baidu.com");
		case (TaskType.Android):
			break;
		case (TaskType.Desktop):
			break;
		}
		return null;
		
	}
	
	public ActionForward goToTest(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		
		return null;
	}
}