/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.controller;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionRedirect;

import cn.com.crowdsourcedtesting.DAO.TestTaskDAO;
import cn.com.crowdsourcedtesting.bean.TestTask;
import cn.com.crowdsourcedtesting.struts.form.TestTaskDetailViewForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.action path="/testTaskDetailView" name="testTaskDetailViewForm" input="/form/testTaskDetailView.jsp" scope="request" validate="true"
 */
public class TestTaskDetailViewAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		TestTaskDetailViewForm testTaskDetailViewForm = (TestTaskDetailViewForm) form;
		Integer testTaskId = testTaskDetailViewForm.getTaskID();
		if (testTaskId == null) {
			return new ActionRedirect(mapping.findForwardConfig("dispPage"));
		}
		TestTaskDAO testTaskDAO = new TestTaskDAO();
		TestTask testTask = testTaskDAO.findById(testTaskId);
		if (testTask == null) {
			return new ActionRedirect(mapping.findForwardConfig("dispPage"));
		}
		request.getSession().setAttribute("TaskDetail", testTask);
		return mapping.findForward("taskDetailPage");
	}
}