/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.aspectj.weaver.patterns.ThisOrTargetAnnotationPointcut;

/** 
 * MyEclipse Struts
 * Creation date: 05-22-2014
 * 
 * XDoclet definition:
 * @struts.form name="changeInformationForm"
 */
public class ChangeInformationForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** email property */
	private String email;

	/** name property */
	private String name;

	/** password property */
	private String password;

	private String password_comfirm;
	/*
	 * Generated Methods
	 */

	

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
//		if (!(this.password.equals(this.password_comfirm))) {
//			System.out.println(this.password);
//			System.out.println(this.password_comfirm);
//			this.password = null;
//		}
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getPassword_comfirm() {
		return password_comfirm;
	}

	public void setPassword_comfirm(String password_comfirm) {
		this.password_comfirm = password_comfirm;
	}
}