/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

/** 
 * MyEclipse Struts
 * Creation date: 05-18-2014
 * 
 * XDoclet definition:
 * @struts.form name="findPasswordForm"
 */
public class FindPasswordForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** email property */
	private String email;

	private String password;
	
	private String password_comfirm;

	private String randomcode;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		ActionErrors errors = new ActionErrors();
		if (!(this.email.equals("null"))) {
			if(this.email.equals(""))
			{
				errors.add("email",new ActionMessage("email.null"));
				request.setAttribute("errors", "null");
			}
			else if (!(this.email.matches("\\w+@\\w+\\.(com\\.cn)|\\w+@\\w+\\.(com|cn)"))) 
			{
				errors.add("email",new ActionMessage("email.wrongformat"));
				request.setAttribute("errors", "wrongformat");
			}
		}
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getRandomcode() {
		return randomcode;
	}

	public void setRandomcode(String randomcode) {
		this.randomcode = randomcode;
	}
	
	public String getPassword_comfirm() {
		return password_comfirm;
	}

	public void setPassword_comfirm(String password_comfirm) {
		this.password_comfirm = password_comfirm;
	}
}