/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-01-2014
 * 
 * XDoclet definition:
 * @struts.form name="giftForm"
 */
public class GiftForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** giftId property */
	private int giftId;

	private int pagenow;
	
	
	/*
	 * Generated Methods
	 */
	
	public int getPagenow() {
		return pagenow;
	}

	public void setPagenow(int pagenow) {
		this.pagenow = pagenow;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the giftId.
	 * @return String
	 */
	public int getGiftId() {
		return giftId;
	}

	/** 
	 * Set the giftId.
	 * @param giftId The giftId to set
	 */
	public void setGiftId(int giftId) {
		this.giftId = giftId;
	}
}