/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-02-2014
 * 
 * XDoclet definition:
 * @struts.form name="publisherQuestionnaireForm"
 */
public class PublisherQuestionnaireForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** questionnaireName property */
	private String questionnaireName;

	/** questionName property */
	private String questionName;
	
	private String choices;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the questionnaireName.
	 * @return String
	 */
	public String getQuestionnaireName() {
		return questionnaireName;
	}

	/** 
	 * Set the questionnaireName.
	 * @param questionnaireName The questionnaireName to set
	 */
	public void setQuestionnaireName(String questionnaireName) {
		this.questionnaireName = questionnaireName;
	}

	/** 
	 * Returns the questionName.
	 * @return String
	 */
	public String getQuestionName() {
		return questionName;
	}

	/** 
	 * Set the questionName.
	 * @param questionName The questionName to set
	 */
	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}
	
	
	/** 
	 * Returns the questionName.
	 * @return String
	 */
	public String getChoices() {
		return choices;
	}

	/** 
	 * Set the questionName.
	 * @param questionName The questionName to set
	 */
	public void setChoices(String choices) {
		this.choices = choices;
	}
}