/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-02-2014
 * 
 * XDoclet definition:
 * @struts.form name="questionForm"
 */
public class QuestionForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** questionnaireName property */
	private String questionnaireName;

	/** choice property */
	private String choice;

	/** questionName property */
	private String questionName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the questionnaireName.
	 * @return String
	 */
	public String getQuestionnaireName() {
		return questionnaireName;
	}

	/** 
	 * Set the questionnaireName.
	 * @param questionnaireName The questionnaireName to set
	 */
	public void setQuestionnaireName(String questionnaireName) {
		this.questionnaireName = questionnaireName;
	}

	/** 
	 * Returns the choice.
	 * @return String
	 */
	public String getChoice() {
		return choice;
	}

	/** 
	 * Set the choice.
	 * @param choice The choice to set
	 */
	public void setChoice(String choice) {
		this.choice = choice;
	}

	/** 
	 * Returns the questionName.
	 * @return String
	 */
	public String getQuestionName() {
		return questionName;
	}

	/** 
	 * Set the questionName.
	 * @param questionName The questionName to set
	 */
	public void setQuestionName(String questionName) {
		this.questionName = questionName;
	}
}