/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-21-2014
 * 
 * XDoclet definition:
 * @struts.form name="questionnaireDisplayForm"
 */
public class QuestionnaireDisplayForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** questionID property */
	private String questionID;

	/** subType property */
	private String subType;

	/** questionnaireID property */
	private String questionnaireID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the questionID.
	 * @return String
	 */
	public String getQuestionID() {
		return questionID;
	}

	/** 
	 * Set the questionID.
	 * @param questionID The questionID to set
	 */
	public void setQuestionID(String questionID) {
		this.questionID = questionID;
	}

	/** 
	 * Returns the subType.
	 * @return String
	 */
	public String getSubType() {
		return subType;
	}

	/** 
	 * Set the subType.
	 * @param subType The subType to set
	 */
	public void setSubType(String subType) {
		this.subType = subType;
	}

	/** 
	 * Returns the questionnaireID.
	 * @return String
	 */
	public String getQuestionnaireID() {
		return questionnaireID;
	}

	/** 
	 * Set the questionnaireID.
	 * @param questionnaireID The questionnaireID to set
	 */
	public void setQuestionnaireID(String questionnaireID) {
		this.questionnaireID = questionnaireID;
	}
}