/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 05-03-2014
 * 
 * XDoclet definition:
 * @struts.form name="registrationPublisherForm"
 */
public class RegistrationPublisherForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** authority property */
	private Boolean authority;

	/** logEmail property */
	private String logEmail;

	/** name property */
	private String name;

	/** type property */
	private Boolean type;

	/** credit property */
	private Double credit;

	/** password property */
	private String password;
	
	private String connectEmail;

	private String code;
	
	private String comfirmCode;
	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		this.authority = false;
		this.credit = 0.0;
		this.type = false;
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the authority.
	 * @return Boolean
	 */
	public Boolean getAuthority() {
		return authority;
	}

	/** 
	 * Set the authority.
	 * @param authority The authority to set
	 */
	public void setAuthority(Boolean authority) {
		this.authority = authority;
	}

	/** 
	 * Returns the logEmail.
	 * @return String
	 */
	public String getLogEmail() {
		return logEmail;
	}

	/** 
	 * Set the logEmail.
	 * @param logEmail The logEmail to set
	 */
	public void setLogEmail(String logEmail) {
		this.logEmail = logEmail;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the type.
	 * @return String
	 */
	public Boolean getType() {
		return type;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setType(Boolean type) {
		this.type = type;
	}

	/** 
	 * Returns the credit.
	 * @return Double
	 */
	public Double getCredit() {
		return credit;
	}

	/** 
	 * Set the credit.
	 * @param credit The credit to set
	 */
	public void setCredit(Double credit) {
		this.credit = credit;
	}

	/** 
	 * Returns the password.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}

	/** 
	 * Set the password.
	 * @param password The password to set
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	
	public String getConnectEmail() {
		return connectEmail;
	}

	public void setConnectEmail(String connectEmail) {
		this.connectEmail = connectEmail;
	}
	
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getComfirmCode() {
		return comfirmCode;
	}

	public void setComfirmCode(String comfirmCode) {
		this.comfirmCode = comfirmCode;
	}
}