/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package cn.com.crowdsourcedtesting.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 05-28-2014
 * 
 * XDoclet definition:
 * @struts.form name="testTaskDetailViewForm"
 */
public class TestTaskDetailViewForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** page property */
	private Integer page;

	/** taskID property */
	private Integer taskID;
	
	private String bugTitle;
	
	private String bugType;
	
	private FormFile bugImage;
	
	private String bugOperation;
	
	private String bugResult;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	@Override
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	@Override
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the page.
	 * @return Integer
	 */
	public Integer getPage() {
		return page;
	}

	/** 
	 * Set the page.
	 * @param page The page to set
	 */
	public void setPage(Integer page) {
		this.page = page;
	}

	/** 
	 * Returns the taskID.
	 * @return String
	 */
	public Integer getTaskID() {
		return taskID;
	}

	/** 
	 * Set the taskID.
	 * @param taskID The taskID to set
	 */
	public void setTaskID(Integer taskID) {
		this.taskID = taskID;
	}

	public String getBugTitle() {
		return bugTitle;
	}

	public void setBugTitle(String bugTitle) {
		this.bugTitle = bugTitle;
	}

	public String getBugType() {
		return bugType;
	}

	public void setBugType(String bugType) {
		this.bugType = bugType;
	}

	public FormFile getBugImage() {
		return bugImage;
	}

	public void setBugImage(FormFile bugImage) {
		this.bugImage = bugImage;
	}

	public String getBugOperation() {
		return bugOperation;
	}

	public void setBugOperation(String bugOperation) {
		this.bugOperation = bugOperation;
	}

	public String getBugResult() {
		return bugResult;
	}

	public void setBugResult(String bugResult) {
		this.bugResult = bugResult;
	}
	
	
}